name: bakerstreet_assignment
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.0
  google_fonts: ^4.0.3
  provider: ^6.0.5
  lottie: ^2.3.1
  pinput: ^2.2.31
  email_validator: ^2.1.17
  date_time_picker: ^2.0.0
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/lottie/
    - assets/png/
  # - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  

